In [1]:
import time
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [2]:
#防止乱码#
mpl.rcParams['font.sans-serif'] = [u'simHei']

In [3]:
#load data#
path='D:/python/exercise/boston_housing.data'
df = pd.read_csv(path, sep=";")

In [4]:
data=np.empty(shape=(len(df),14))
for idx,value in enumerate(df.values):
    value=value[0]
    values=value.split(" ")
    values=filter(lambda v:v !="", values)
    data[idx]=list(values)
data= data.astype(np.float32)
print(data)
print(data.shape)

[[2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 [3.2370e-02 0.0000e+00 2.1800e+00 ... 3.9463e+02 2.9400e+00 3.3400e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
(505, 14)


In [5]:
#区分x,y#
x,y=np.split(data,(13,),axis=1)
y=y.ravel()
print(x.shape)
print(y.shape[0])

(505, 13)
505


In [6]:
#train-test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)

(404, 13)
(404,)


In [7]:
#线性回归1阶#
poly=PolynomialFeatures(degree=1)
x_train=poly.fit_transform(x_train)
x_test=poly.transform(x_test)
algo=LinearRegression(fit_intercept=True)
algo.fit(x_train,y_train)
#模型结果#
print("截距项值:{}".format(algo.intercept_))
print("1阶训练集上r2:{}".format(algo.score(x_train,y_train)))
print("1阶测试集上r2:{}".format(algo.score(x_test,y_test)))
#线性回归2阶#
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
poly=PolynomialFeatures(degree=2)
x_train=poly.fit_transform(x_train)
x_test=poly.transform(x_test)
algo=LinearRegression(fit_intercept=True)
algo.fit(x_train,y_train)
#模型结果#
print("截距项值:{}".format(algo.intercept_))
print("2阶训练集上r2:{}".format(algo.score(x_train,y_train)))
print("2阶测试集上r2:{}".format(algo.score(x_test,y_test)))
#线性回归3阶#
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
poly=PolynomialFeatures(degree=3)
x_train=poly.fit_transform(x_train)
x_test=poly.transform(x_test)
algo=LinearRegression(fit_intercept=True)
algo.fit(x_train,y_train)
#模型结果#
print("截距项值:{}".format(algo.intercept_))
print("3阶训练集上r2:{}".format(algo.score(x_train,y_train)))
print("3阶测试集上r2:{}".format(algo.score(x_test,y_test)))

截距项值:37.69016647338867
1阶训练集上r2:0.7275841947025221
1阶测试集上r2:0.7881077692975853
截距项值:-68.39421844482422
2阶训练集上r2:0.9254615297264116
2阶测试集上r2:0.8578178774254438
截距项值:28.853120803833008
3阶训练集上r2:0.9615651543308162
3阶测试集上r2:0.5692648789938042
